-- MySQL Script generated by MySQL Workbench
-- 01/02/15 17:17:00
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema projetlj
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projetlj
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projetlj` DEFAULT CHARACTER SET utf8 ;
USE `projetlj` ;

-- -----------------------------------------------------
-- Table `projetlj`.`badges`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetlj`.`badges` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name_badge` VARCHAR(30) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `comment_badge` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `badges_name_badge_unique` (`name_badge` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `projetlj`.`countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetlj`.`countries` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name_country` VARCHAR(30) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `code_country` VARCHAR(5) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `countries_name_country_unique` (`name_country` ASC),
  UNIQUE INDEX `countries_code_country_unique` (`code_country` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `projetlj`.`cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetlj`.`cities` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name_city` VARCHAR(30) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `country_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `cities_country_id_foreign` (`country_id` ASC),
  CONSTRAINT `cities_country_id_foreign`
    FOREIGN KEY (`country_id`)
    REFERENCES `projetlj`.`countries` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `projetlj`.`sportsmen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetlj`.`sportsmen` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `lastname_sportsman` VARCHAR(30) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `firstname_sportsman` VARCHAR(30) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `date_birthday` DATE NULL DEFAULT NULL,
  `size` SMALLINT(6) NULL DEFAULT NULL,
  `weight` SMALLINT(6) NULL DEFAULT NULL,
  `picture` VARCHAR(7) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `country_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `sportsmen_country_id_foreign` (`country_id` ASC),
  CONSTRAINT `sportsmen_country_id_foreign`
    FOREIGN KEY (`country_id`)
    REFERENCES `projetlj`.`countries` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `projetlj`.`languages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetlj`.`languages` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name_language` VARCHAR(30) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `code_language` VARCHAR(5) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `languages_name_language_unique` (`name_language` ASC),
  UNIQUE INDEX `languages_code_language_unique` (`code_language` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `projetlj`.`sports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetlj`.`sports` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name_sport` VARCHAR(30) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `projetlj`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetlj`.`users` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `date_registration` DATETIME NOT NULL,
  `nickname` VARCHAR(30) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `email` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `password` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `lastname` VARCHAR(30) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `firstname` VARCHAR(30) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `date_birthday` DATE NULL DEFAULT NULL,
  `sexe` TINYINT(1) NULL DEFAULT NULL,
  `picture` VARCHAR(7) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `comment_user` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `nbr_messages` INT(11) NOT NULL DEFAULT '0',
  `date_lastConnection` DATETIME NOT NULL,
  `online` TINYINT(4) NOT NULL DEFAULT '0',
  `status_account` TINYINT(4) NOT NULL DEFAULT '0',
  `sport_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `city_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `country_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `language_id` INT(10) UNSIGNED NOT NULL DEFAULT '1',
  `remember_token` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `users_nickname_unique` (`nickname` ASC),
  UNIQUE INDEX `users_email_unique` (`email` ASC),
  INDEX `users_sport_id_foreign` (`sport_id` ASC),
  INDEX `users_city_id_foreign` (`city_id` ASC),
  INDEX `users_country_id_foreign` (`country_id` ASC),
  INDEX `users_language_id_foreign` (`language_id` ASC),
  CONSTRAINT `users_city_id_foreign`
    FOREIGN KEY (`city_id`)
    REFERENCES `projetlj`.`cities` (`id`),
  CONSTRAINT `users_country_id_foreign`
    FOREIGN KEY (`country_id`)
    REFERENCES `projetlj`.`countries` (`id`),
  CONSTRAINT `users_language_id_foreign`
    FOREIGN KEY (`language_id`)
    REFERENCES `projetlj`.`languages` (`id`),
  CONSTRAINT `users_sport_id_foreign`
    FOREIGN KEY (`sport_id`)
    REFERENCES `projetlj`.`sports` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `projetlj`.`comment_sportsman`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetlj`.`comment_sportsman` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `date_comment` DATETIME NOT NULL,
  `content` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `user_id` INT(10) UNSIGNED NOT NULL,
  `sportsman_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `comment_sportsman_user_id_foreign` (`user_id` ASC),
  INDEX `comment_sportsman_sportsman_id_foreign` (`sportsman_id` ASC),
  CONSTRAINT `comment_sportsman_sportsman_id_foreign`
    FOREIGN KEY (`sportsman_id`)
    REFERENCES `projetlj`.`sportsmen` (`id`),
  CONSTRAINT `comment_sportsman_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `projetlj`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `projetlj`.`divisions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetlj`.`divisions` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name_division` VARCHAR(15) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `projetlj`.`teams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetlj`.`teams` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name_team` VARCHAR(30) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `flag` VARCHAR(7) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `country_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `sport_id` INT(10) UNSIGNED NOT NULL,
  `division_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `teams_country_id_foreign` (`country_id` ASC),
  INDEX `teams_sport_id_foreign` (`sport_id` ASC),
  INDEX `teams_division_id_foreign` (`division_id` ASC),
  CONSTRAINT `teams_country_id_foreign`
    FOREIGN KEY (`country_id`)
    REFERENCES `projetlj`.`countries` (`id`),
  CONSTRAINT `teams_division_id_foreign`
    FOREIGN KEY (`division_id`)
    REFERENCES `projetlj`.`divisions` (`id`),
  CONSTRAINT `teams_sport_id_foreign`
    FOREIGN KEY (`sport_id`)
    REFERENCES `projetlj`.`sports` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `projetlj`.`comment_team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetlj`.`comment_team` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `date_comment` DATETIME NOT NULL,
  `content` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `user_id` INT(10) UNSIGNED NOT NULL,
  `team_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `comment_team_user_id_foreign` (`user_id` ASC),
  INDEX `comment_team_team_id_foreign` (`team_id` ASC),
  CONSTRAINT `comment_team_team_id_foreign`
    FOREIGN KEY (`team_id`)
    REFERENCES `projetlj`.`teams` (`id`),
  CONSTRAINT `comment_team_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `projetlj`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `projetlj`.`features`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetlj`.`features` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name_feature` VARCHAR(30) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `features_name_feature_unique` (`name_feature` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `projetlj`.`feature_sport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetlj`.`feature_sport` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `sport_id` INT(10) UNSIGNED NOT NULL,
  `feature_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `feature_sport_sport_id_foreign` (`sport_id` ASC),
  INDEX `feature_sport_feature_id_foreign` (`feature_id` ASC),
  CONSTRAINT `feature_sport_feature_id_foreign`
    FOREIGN KEY (`feature_id`)
    REFERENCES `projetlj`.`features` (`id`),
  CONSTRAINT `feature_sport_sport_id_foreign`
    FOREIGN KEY (`sport_id`)
    REFERENCES `projetlj`.`sports` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `projetlj`.`sportsman_sport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetlj`.`sportsman_sport` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `sport_id` INT(10) UNSIGNED NOT NULL,
  `sportsman_id` INT(10) UNSIGNED NOT NULL,
  `period_begin` DATE NULL DEFAULT NULL,
  `period_end` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `sportsman_sport_sport_id_foreign` (`sport_id` ASC),
  INDEX `sportsman_sport_sportsman_id_foreign` (`sportsman_id` ASC),
  CONSTRAINT `sportsman_sport_sportsman_id_foreign`
    FOREIGN KEY (`sportsman_id`)
    REFERENCES `projetlj`.`sportsmen` (`id`),
  CONSTRAINT `sportsman_sport_sport_id_foreign`
    FOREIGN KEY (`sport_id`)
    REFERENCES `projetlj`.`sports` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `projetlj`.`feature_sportsman_sport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetlj`.`feature_sportsman_sport` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `sportsman_sport_id` INT(10) UNSIGNED NOT NULL,
  `feature_id` INT(10) UNSIGNED NOT NULL,
  `feature_value` VARCHAR(30) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `feature_sportsman_sport_sportsman_sport_id_foreign` (`sportsman_sport_id` ASC),
  INDEX `feature_sportsman_sport_feature_id_foreign` (`feature_id` ASC),
  CONSTRAINT `feature_sportsman_sport_feature_id_foreign`
    FOREIGN KEY (`feature_id`)
    REFERENCES `projetlj`.`features` (`id`),
  CONSTRAINT `feature_sportsman_sport_sportsman_sport_id_foreign`
    FOREIGN KEY (`sportsman_sport_id`)
    REFERENCES `projetlj`.`sportsman_sport` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `projetlj`.`migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetlj`.`migrations` (
  `migration` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `batch` INT(11) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `projetlj`.`password_reminders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetlj`.`password_reminders` (
  `email` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `token` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  INDEX `password_reminders_email_index` (`email` ASC),
  INDEX `password_reminders_token_index` (`token` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `projetlj`.`positions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetlj`.`positions` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name_position` VARCHAR(30) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `code_position` VARCHAR(5) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `positions_name_position_unique` (`name_position` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `projetlj`.`position_sport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetlj`.`position_sport` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `sport_id` INT(10) UNSIGNED NOT NULL,
  `position_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `position_sport_sport_id_foreign` (`sport_id` ASC),
  INDEX `position_sport_position_id_foreign` (`position_id` ASC),
  CONSTRAINT `position_sport_position_id_foreign`
    FOREIGN KEY (`position_id`)
    REFERENCES `projetlj`.`positions` (`id`),
  CONSTRAINT `position_sport_sport_id_foreign`
    FOREIGN KEY (`sport_id`)
    REFERENCES `projetlj`.`sports` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `projetlj`.`skills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetlj`.`skills` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name_skill` VARCHAR(30) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `skills_name_skill_unique` (`name_skill` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `projetlj`.`sportsman_position_sport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetlj`.`sportsman_position_sport` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `position_sport_id` INT(10) UNSIGNED NOT NULL,
  `sportsman_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `sportsman_position_sport_position_sport_id_foreign` (`position_sport_id` ASC),
  INDEX `sportsman_position_sport_sportsman_id_foreign` (`sportsman_id` ASC),
  CONSTRAINT `sportsman_position_sport_position_sport_id_foreign`
    FOREIGN KEY (`position_sport_id`)
    REFERENCES `projetlj`.`position_sport` (`id`),
  CONSTRAINT `sportsman_position_sport_sportsman_id_foreign`
    FOREIGN KEY (`sportsman_id`)
    REFERENCES `projetlj`.`sportsmen` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `projetlj`.`skill_sportsman`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetlj`.`skill_sportsman` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `sportsman_position_sport_id` INT(10) UNSIGNED NOT NULL,
  `skill_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `skill_sportsman_sportsman_position_sport_id_foreign` (`sportsman_position_sport_id` ASC),
  INDEX `skill_sportsman_skill_id_foreign` (`skill_id` ASC),
  CONSTRAINT `skill_sportsman_skill_id_foreign`
    FOREIGN KEY (`skill_id`)
    REFERENCES `projetlj`.`skills` (`id`),
  CONSTRAINT `skill_sportsman_sportsman_position_sport_id_foreign`
    FOREIGN KEY (`sportsman_position_sport_id`)
    REFERENCES `projetlj`.`sportsman_position_sport` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `projetlj`.`rating_sportsman`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetlj`.`rating_sportsman` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(10) UNSIGNED NOT NULL,
  `skill_sportsman_id` INT(10) UNSIGNED NOT NULL,
  `value_rate` TINYINT(3) UNSIGNED NOT NULL,
  `date_rate` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `rating_sportsman_user_id_foreign` (`user_id` ASC),
  INDEX `rating_sportsman_skill_sportsman_id_foreign` (`skill_sportsman_id` ASC),
  CONSTRAINT `rating_sportsman_skill_sportsman_id_foreign`
    FOREIGN KEY (`skill_sportsman_id`)
    REFERENCES `projetlj`.`skill_sportsman` (`id`),
  CONSTRAINT `rating_sportsman_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `projetlj`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `projetlj`.`team_skill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetlj`.`team_skill` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `team_id` INT(10) UNSIGNED NOT NULL,
  `skill_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `team_skill_team_id_foreign` (`team_id` ASC),
  CONSTRAINT `team_skill_team_id_foreign`
    FOREIGN KEY (`team_id`)
    REFERENCES `projetlj`.`teams` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `projetlj`.`rating_team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetlj`.`rating_team` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(10) UNSIGNED NOT NULL,
  `team_skill_id` INT(10) UNSIGNED NOT NULL,
  `value_rate` TINYINT(3) UNSIGNED NOT NULL,
  `date_rate` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `rating_team_user_id_foreign` (`user_id` ASC),
  INDEX `rating_team_team_skill_id_foreign` (`team_skill_id` ASC),
  CONSTRAINT `rating_team_team_skill_id_foreign`
    FOREIGN KEY (`team_skill_id`)
    REFERENCES `projetlj`.`team_skill` (`id`),
  CONSTRAINT `rating_team_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `projetlj`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `projetlj`.`team_feature`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetlj`.`team_feature` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `team_id` INT(11) NOT NULL,
  `feature_id` INT(10) UNSIGNED NOT NULL,
  `feature_value` VARCHAR(30) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `team_feature_feature_id_foreign` (`feature_id` ASC),
  CONSTRAINT `team_feature_feature_id_foreign`
    FOREIGN KEY (`feature_id`)
    REFERENCES `projetlj`.`features` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `projetlj`.`team_sportsman`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetlj`.`team_sportsman` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `team_id` INT(10) UNSIGNED NOT NULL,
  `sportsman_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `team_sportsman_team_id_foreign` (`team_id` ASC),
  INDEX `team_sportsman_sportsman_id_foreign` (`sportsman_id` ASC),
  CONSTRAINT `team_sportsman_sportsman_id_foreign`
    FOREIGN KEY (`sportsman_id`)
    REFERENCES `projetlj`.`sportsmen` (`id`),
  CONSTRAINT `team_sportsman_team_id_foreign`
    FOREIGN KEY (`team_id`)
    REFERENCES `projetlj`.`teams` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `projetlj`.`user_badge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetlj`.`user_badge` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `badge_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `date_badge` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_badge_user_id_foreign` (`user_id` ASC),
  INDEX `user_badge_badge_id_foreign` (`badge_id` ASC),
  CONSTRAINT `user_badge_badge_id_foreign`
    FOREIGN KEY (`badge_id`)
    REFERENCES `projetlj`.`badges` (`id`),
  CONSTRAINT `user_badge_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `projetlj`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `projetlj`.`user_sportsman`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetlj`.`user_sportsman` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `sportsman_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `like_sportsman` TINYINT(1) NULL DEFAULT '0',
  `favorite_sportsman` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `user_sportsman_user_id_foreign` (`user_id` ASC),
  INDEX `user_sportsman_sportsman_id_foreign` (`sportsman_id` ASC),
  CONSTRAINT `user_sportsman_sportsman_id_foreign`
    FOREIGN KEY (`sportsman_id`)
    REFERENCES `projetlj`.`sportsmen` (`id`),
  CONSTRAINT `user_sportsman_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `projetlj`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `projetlj`.`user_team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetlj`.`user_team` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `team_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `like_team` TINYINT(1) NULL DEFAULT NULL,
  `favorite_team` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_team_user_id_foreign` (`user_id` ASC),
  INDEX `user_team_team_id_foreign` (`team_id` ASC),
  CONSTRAINT `user_team_team_id_foreign`
    FOREIGN KEY (`team_id`)
    REFERENCES `projetlj`.`teams` (`id`),
  CONSTRAINT `user_team_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `projetlj`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
